language: node_js
node_js:
- v8
- v7
- v6
- v5
- v4
deploy:
  provider: npm
  email: wouter.dullaert@gmail.com
  api_key:
    secure: FJCynTxKqEZDMs5LBHYJIeyyfUxwaWOwNmS2NlmOpZ0Jc1NVlnwIU6++Jx2eVnFtp13k7pbs37tBPusfEtVrUATFkj+LsX/Vwybz772vkv0C6j7lnQJGAt5UYPmNPXn7pkHA+0qbnCYt/zJJWi43zK/uemQA1r34p7MzalckHHm41pQCpQIwMhw14cKM4ytYy7af2ondkD1FwbOupibuVCHZy4NZH8bcz2dOZVSlzgWjrrNncCzJ7bOjWSlPafzsHRPkjxP68bJUO/8WTwRAl6UlRzg5Rc9CqGOcmPjcCM8A28p6e/ZrttVjSrnyrDhw2GCPg2KfVtYs1afRj7GyPoCqWymVRNBhFI3C5Qkqu2ZcdAEhl7f0mFvgijAqcb4BIfL5oU6dtp1rxFoHZ73b8YLXzXpgZdOSRK379Org2lkbAEmKWqtyRx7EJq/wEIHgIufNcRHDM/5kskIIncA98xg4UTwkFnp9sTQG4+gT9nEYAXlhx8jpy/Ja/FlvVYLY0L/XyEuGywskZhZV6tvJSfK9iP0p5p8cJ7ZyE+IQ5tbO/GErdagrdYuXwD4ohMiJPew+NJundSD0kcuGtvDf0B9FoVyQmbXk1aCEIY46An3xx1VrqHFalzl6LlG7lhZsbXOdZwKNNI9wauxkmondVOoM45bioQJ6MoKnhbMQlhU=
  on:
    tags: true
    node: v6
