language: node_js
node_js:
- v7
- v6
- v5
- v4
deploy:
  provider: npm
  email: wouter.dullaert@gmail.com
  api_key:
    secure: hZdbzALrE3vkzyiWpSiaZoZcdyQvzu6XLpO4XtkACSiFVTPdtcnZXK5wI04gVZ600uQA+Q+oRwT2WmGBmNsB6n0AsN+3zYYxunLracXIHgZCO9I0JrrKOXvW1oNDY2IEbJN2T/SwAHNzETlUXNLJaFlmdg0tNkqeLX+78j8JN1tIihuwjDs+EgJkaQd+k2b4+ie/6rcqkdQaqWYp0sv+jBfkwyD4b2elOfN0tdedfDqfvWTUJDJB0Obnfb5HvV2ctlC+bYpvBxx6olI7afA9YeJGMk3kbxhfsKllsaZJVmEjL/N3lRxquPEvPUWruO0wWCsLJfT2AgkAKPa6jCuTHBYFqgC/z9RBt9Ol65b5C4RYV2HOTEYpDHmazW6GT9k6Vrqd9dWNeltnR/oZoLfWtcIUfICj9tHFM8oPZuRHuEoIIU+YZx3ClYn7XFdxJuTZR2OIwsOCkXFXZLBvM0cda9GyYdjDyziwZH6Pnnje5llEfGlJCVqifg8j6KD/uhSATVIiGCskb0Ladvc2JFACt3eiIx4YO6ah17mX4qDaKbNqeTZ2m6VfYDRukJg3kNt59hfHUNIrPdzfVbF3PfBMHK+GJul/nDvpW5FLnkcDBxV90i1g+KT68scK7w0B2FOGCUWOdsZ3f3kAc8W3xidyHQYnW/hkUgY+AOTMonOgpjk=
  on:
    tags: true
    node: v6
